name: VendEx
version: 1.1
description: Player vending plugin for Shadowraze Network
author: SirReason

main: net.shadowraze.vendex.VendEx
depend: [Vault, WorldGuard]
softdepend: [VotingRewards]

commands:
  menu:
    description: Main menu management command
    usage: Syntax error! Type /menu help for assistance
  shop:
    description: Main shop management command
    usage: Syntax error! Type /shop help for assistance
  market:
    description: Main market management command
    usage: Syntax error! Type /market help for assistance
  trade:
    description: Main trade management command
    usage: Syntax error! Type /trade help for assistance